//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecetarioMVC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int cod_menu { get; set; }
        public int cod_receta { get; set; }
        public string nombre_menu { get; set; }
        public decimal precio_menu { get; set; }
        public string comentario_menu { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual receta receta { get; set; }
    }
}
