//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecetarioMVC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plato
    {
        public int cod_plato { get; set; }
        public int cod_receta { get; set; }
        public string tipo_plato { get; set; }
        public string ingredientes_principal { get; set; }
        public decimal precio { get; set; }
        public string comentario { get; set; }
        public string nombre { get; set; }
        public string calorias { get; set; }
        public decimal cant_ingredientes { get; set; }
        public string porcion { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual receta receta { get; set; }
    }
}
