//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecetarioMVC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public receta()
        {
            this.menu = new HashSet<menu>();
            this.plato = new HashSet<plato>();
        }
    
        public int cod_receta { get; set; }
        public string fuente_receta { get; set; }
        public string ubicacion_fisica_receta { get; set; }
        public string lista_ingredientes_receta { get; set; }
        public string utensilios_receta { get; set; }
        public string comentario_receta { get; set; }
        public System.TimeSpan tiempo_receta { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menu> menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plato> plato { get; set; }
    }
}
